import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://my.shuttlers.co/auth/login');
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('jamesswagz24@gmail.com');
  await page.getByRole('textbox', { name: 'Password Login with OTP' }).click();
  await page.getByRole('textbox', { name: 'Password Login with OTP' }).fill('TestPassword');
  await page.locator('[data-test="login-button"]').click();
  await page.getByRole('link', { name: 'Hire a Vehicle' }).click();
  await page.getByRole('article').filter({ hasText: 'Shuttlers BlackExperience' }).click();
  await page.getByRole('article').filter({ hasText: 'Coaster Bus - New Shape(2017' }).click();
  await page.locator('[data-test-id="chat-widget-iframe"]').contentFrame().locator('[data-test-id="welcome-message-close-button"]').click();
  await page.getByRole('button', { name: '+' }).click();
  await page.getByRole('button', { name: '−' }).click();
  await page.getByRole('button', { name: 'Add to charter' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('1234');
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page.getByText('21', { exact: true }).click();
  await page.getByRole('textbox').nth(2).click();
  await page.getByText('02').first().click();
  await page.getByText('01').nth(3).click();
  await page.getByText('PM', { exact: true }).click();
  await page.getByRole('button', { name: 'proceed' }).click();
  await page.getByRole('textbox', { name: 'Pick up location' }).click();
  await page.getByRole('textbox', { name: 'Pick up location' }).fill('Lekki');
  await page.getByText('Lekki Phase 1, Lekki, Nigeria').click();
  await page.getByRole('textbox', { name: 'Search destination' }).click();
  await page.getByRole('textbox', { name: 'Search destination' }).fill('1st av');
  await page.getByText('Festac Town, 1st Avenue,').first().click();
  await page.getByRole('button', { name: 'Assign vehicle' }).click();
  await page.getByRole('article').filter({ hasText: 'Coaster Bus - New Shape27' }).click();
  await page.getByRole('button', { name: 'Assign to location' }).click();
  await page.getByRole('button', { name: 'proceed' }).click();
  await page.getByRole('checkbox', { name: 'I agree that the total amount' }).check();
  //await page.getByRole('button', { name: 'Send request' }).click();
  //await page.getByRole('button', { name: 'Close' }).click();
});